### ISSUE TITLE
Segmentation fault (core dumped) on AMD Instinct™ MI100

### ISSUE THREAD

**Issue by chenchiii** [Minimap2onGPU/minimap2#15]
### Description:
While executing the code from the `gpu_kernel` (default)  branch on an AMD Instinct™ MI100, I encountered a segmentation fault. Below are the details of the environment and the steps I followed:

### Environment:
Hardware: AMD Instinct™ MI100
ROCm Versions Tested:
```
----------------------------------------------------------- /opt/ohpc/pub/modulefiles -----------------------------------------------------
rocm/5.4.2    rocm/5.5.1    rocm/5.7.1 (L)    rocm/6.0.2 (D)
  Where:
   L:  Module is loaded
   D:  Default Module
  If the avail list is too long consider trying:
  
  "module --default avail" or "ml -d av" to just list the default modules.
  "module overview" or "ml ov" to display the number of modules for each name.
  
  Use "module spider" to find all possible modules and extensions.
  Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".
```

### Steps to Reproduce:

1. Compiled the code with the following command:
`make GPU=AMD DEBUG=analyze`
[build_log](https://github.com/Minimap2onGPU/mm2-gb/files/15442115/build_log.txt)

2. Executed Minimap2 with the command provided in the README:
`./minimap2 -t 1 --gpu-chain --gpu-cfg gpu/gpu_config.json test/MT-human.fa test/MT-orang.fa > mm2-gb_out.paf`

Observed Behavior:
Received the following segmentation fault message:
```
[student65@login1 mm2-gb]$ ./minimap2 -t 1 --gpu-chain --gpu-cfg gpu/gpu_config.json test/MT-human.fa test/MT-orang.fa > mm2-gb_out.paf
[M::mm_idx_gen::0.001*14.57] collected minimizers
Segmentation fault (core dumped)
[student65@login1 mm2-gb]$ 
```

### Troubleshooting Attempts:
1. Suspecting the issue might not be related to memory limitations, I modified max_total_n and max_read to 500 in _./gpu/gpu_config.json_ but encountered the same segmentation fault:
```
{
    ...
    "max_total_n": 500, 
    "max_read": 500,
    ...
}
```
2. tried different rocm versions
3. make clean before executing `make GPU=AMD DEBUG=analyze`

**Comment by chenchiii** [comment]
Could you please investigate this segmentation fault issue? Any guidance or suggestions for further debugging steps would be appreciated.

Thank you for your assistance.

**Comment by xenshinu** [comment]
Thanks for pointing this out. This bug has been fixed. Please fetch the latest update code.

**Comment by chenchiii** [comment]
it works! Thanks
